ATENCION:

PARA LA CREACION DE FUNCIONES EN POSTGRE

SI EXISTE UNA TRANSACCION EN CURSO; begin transaction;
REALIZADO Y NO CONFIRMADO NI DESCARTADO

Y EJECUTAN SCRIPTS DE CREACION DE FUNCIONES:


POSTGRE EJECUTA EL SCRIPT SIN INDICAR O EMITIR MENSAJE DE ERROR DE CREACION DE LA FUNCION
Y NO CREA LA FUNCION O BIEN NO LA REMPLAZA: create or replace function

SE DEBE DESCARTAR O CONFIRMAR LA TRANSACCIÓN PARA POSTERIORMENTE EJECUTAR EL SCRIPT DE CRACION DEL OBJECTO
