package py.com.kyron.sgp.persistence.stockmanagement.dao;

import java.util.List;

import py.com.kyron.sgp.bussines.cash.movements.management.domain.CreditNoteItemDTO;
import py.com.kyron.sgp.bussines.stockmanagement.domain.SIItemPDMProductInstanceInvolvedDTO;
import py.com.kyron.sgp.bussines.stockmanagement.domain.SaleInvoiceItemProductDeliverablesDTO;
import py.com.kyron.sgp.bussines.stockmanagement.domain.SaleInvoiceItemProductDepositMovementDTO;
import py.com.kyron.sgp.bussines.stockmanagement.domain.SaleInvoiceProductDeliverablesDTO;
import py.com.kyron.sgp.bussines.stockmanagement.domain.SaleInvoiceProductDepositMovementDTO;

public interface ProductDepositMovementDAO {

	public List<SaleInvoiceProductDeliverablesDTO> listSaleInvoiceProductDeliverablesDTO(SaleInvoiceProductDeliverablesDTO SaleInvoiceProductDeliverablesDTO);
	public List<SaleInvoiceItemProductDeliverablesDTO> listSaleInvoiceItemProductDeliverablesDTO(SaleInvoiceItemProductDeliverablesDTO SaleInvoiceItemProductDeliverablesDTO);
	public Long pmsProductDepositMovementIdentifierNumberBySequence();
	public void effectuateProductDeliverSaleInvoiceItemProductDeliverablesDTO(SaleInvoiceItemProductDeliverablesDTO SaleInvoiceItemProductDeliverablesDTO);
	
	public List<SaleInvoiceProductDepositMovementDTO> listSaleInvoiceProductDepositMovementDTO(SaleInvoiceProductDepositMovementDTO SaleInvoiceProductDepositMovementDTO);
	public List<SaleInvoiceItemProductDepositMovementDTO> listSaleInvoiceItemProductDepositMovementDTO(SaleInvoiceItemProductDepositMovementDTO SaleInvoiceItemProductDepositMovementDTO);
	public List<SIItemPDMProductInstanceInvolvedDTO> listSIItemPDMProductInstanceInvolvedDTO(SIItemPDMProductInstanceInvolvedDTO SIItemPDMProductInstanceInvolvedDTO);
	public List<SIItemPDMProductInstanceInvolvedDTO> listSIItemPDMProductInstanceInvolvedDTOBySaleInvoiceItemProductDeliverablesDTO(SaleInvoiceItemProductDeliverablesDTO SaleInvoiceItemProductDeliverablesDTO);
	
	/**/
	public List<SIItemPDMProductInstanceInvolvedDTO> listProductInstancesReturnableByCreditNoteItemDTO(CreditNoteItemDTO CreditNoteItemDTO);	
	public void effectuateProductReturnSIItemPDMProductInstanceInvolvedDTO(SIItemPDMProductInstanceInvolvedDTO SIItemPDMProductInstanceInvolvedDTO);
	public List<SIItemPDMProductInstanceInvolvedDTO> listProductInstancesReturnedByCreditNoteItemDTO(CreditNoteItemDTO CreditNoteItemDTO);
}
